/*
 * File: app/view/DirectTransfer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finappsparty.view.DirectTransfer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.directTransferAlias',

    config: {
        id: 'directTransfer',
        itemId: 'directTransfer',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Transferencia',
                items: [
                    {
                        xtype: 'button',
                        id: 'logoutButton',
                        itemId: 'logoutButton',
                        text: 'Cerrar'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'hiddenfield',
                id: 'userIdField',
                itemId: 'userIdField',
                name: 'userId'
            },
            {
                xtype: 'hiddenfield',
                id: 'userNameField',
                itemId: 'userNameField',
                name: 'name'
            },
            {
                xtype: 'hiddenfield',
                id: 'userLastnameField',
                itemId: 'userLastnameField',
                name: 'lastname'
            },
            {
                xtype: 'hiddenfield',
                id: 'latField',
                itemId: 'latField',
                name: 'lat'
            },
            {
                xtype: 'hiddenfield',
                id: 'lonField',
                itemId: 'lonField',
                name: 'lon'
            },
            {
                xtype: 'fieldset',
                title: 'Importe',
                items: [
                    {
                        xtype: 'numberfield',
                        id: 'amountField',
                        itemId: 'amountField',
                        inputCls: 'inputLarge',
                        name: 'amount'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                hidden: true,
                title: 'Concepto',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'conceptField',
                        itemId: 'conceptField',
                        name: 'concept',
                        value: 'Shake & Pay'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Número de cuenta',
                items: [
                    {
                        xtype: 'hiddenfield',
                        id: 'accountHiddenField',
                        itemId: 'accountHiddenField',
                        name: 'accn'
                    }
                ]
            },
            {
                xtype: 'carousel',
                height: '125px',
                id: 'accountCarousel',
                itemId: 'accountCarousel',
                scrollable: false
            },
            {
                xtype: 'button',
                cls: 'mainButton',
                id: 'searchTransferButton',
                itemId: 'searchTransferButton',
                ui: 'confirm',
                text: 'Receive money'
            }
        ]
    }

});