/*
 * File: app/view/PayerPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finappsparty.view.PayerPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.payerPanelAlias',

    config: {
        centered: true,
        hidden: true,
        id: 'payerPanel',
        itemId: 'payerPanel',
        styleHtmlContent: true,
        hideOnMaskTap: true,
        modal: true,
        scrollable: 'vertical',
        cls: [
            'modalPanel'
        ],
        hideAnimation: {
            type: 'popOut',
            duration: 250,
            easing: 'ease-in'
        },
        showAnimation: {
            type: 'popIn',
            duration: 250,
            easing: 'ease-out'
        },
        tpl: [
            '<div>',
            '    <span>Busque el número {operationNumber} e introduzca la clave correspondiente.</span>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label">',
            '        <span>Beneficiario</span>',
            '    </div>',
            '    <div class="x-input-el value">',
            '        <span>{name} {lastname}</span>',
            '    </div>',
            '</div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label">',
            '        <span>Cuenta beneficiario</span>',
            '    </div>',
            '    <div class="x-input-el value">',
            '        <span>{account}</span>',
            '    </div>',
            '<div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">    ',
            '    <div class="x-form-label label myLabel">',
            '        <span>Cuenta ordenante</span>',
            '    </div>',
            '    <div class="x-input-el value myValue">',
            '        <span>{payerAccount}</span>',
            '    </div>',
            '<div>',
            '<div class="x-container x-field-text x-field x-label-align-top x-field-labeled x-form-label-nowrap x-empty">        ',
            '    <div class="x-form-label label myLabel">',
            '        <span>Importe</span>',
            '    </div>',
            '    <div class="x-input-el value myValue">',
            '        <span>{amount} €</span>',
            '    </div>',
            '</div>'
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Beneficiario encontrado'
            },
            {
                xtype: 'fieldset',
                cls: [
                    'operationNumberFieldSet'
                ],
                title: 'Confirme la operación',
                items: [
                    {
                        xtype: 'passwordfield',
                        id: 'passOperationField',
                        itemId: 'passOperationField',
                        label: 'Clave',
                        labelWidth: '50%'
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: '100px',
                defaults: {
                    flex: 1
                },
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'actionButton',
                        id: 'payerCancelAction',
                        itemId: 'payerCancelAction',
                        ui: 'decline',
                        text: 'Cancelar'
                    },
                    {
                        xtype: 'button',
                        cls: 'actionButton',
                        id: 'payerOkAction',
                        itemId: 'payerOkAction',
                        ui: 'confirm',
                        text: 'Aceptar'
                    }
                ]
            }
        ]
    }

});