/*
 * File: app/controller/BeneficiaryController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finappsparty.controller.BeneficiaryController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#beneficiaryCancelButton": {
                tap: 'onBeneficiaryCancelButtonTap'
            },
            "#beneficiaryOkButton": {
                tap: 'onBeneficiaryOkButtonTap'
            }
        }
    },

    onBeneficiaryCancelButtonTap: function(button, e, options) {
        this.cancelBeneficiaryOperation();
    },

    onBeneficiaryOkButtonTap: function(button, e, options) {
        this.acceptBeneficiaryOperation();
    },

    cancelBeneficiaryOperation: function() {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: ' Operación rechazada ',
            indicator: false
        });
        setTimeout(function(){
            Ext.Viewport.setMasked(false);
            Ext.getCmp('beneficiaryPanel').hide();
        },1000);

    },

    acceptBeneficiaryOperation: function() {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: ' Operación autorizada ',
            indicator: false
        });
        setTimeout(function(){
            Ext.Viewport.setMasked(false);
            Ext.getCmp('beneficiaryPanel').hide();
        },1000);
    }

});