/*
 * File: app/controller/CardController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finappsparty.controller.CardController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#closeCardPanel": {
                tap: 'onCloseCardPanelTap'
            },
            "#accountButton": {
                tap: 'onAccountButtonTap'
            },
            "#payCardButton": {
                tap: 'onPayCardButtonTap'
            },
            "#cardPanel": {
                initialize: 'onCardPanelInitialize'
            }
        }
    },

    onCloseCardPanelTap: function(button, e, options) {
        this.getApplication().getController('LoginController').showLogin();
    },

    onAccountButtonTap: function(button, e, options) {
        this.getApplication().getController('MainController').changeView('directTransfer');
    },

    onPayCardButtonTap: function(button, e, options) {
        alert('preparar el pago con tarjeta');
    },

    onCardPanelInitialize: function(component, options) {
        this.createCardSelectCarousel();
    },

    createCardSelectCarousel: function() {
        var store = Ext.getStore('Card');
        var n = store.data.items.length;
        if (n !== 0) {
            // Se selecciona automáticamente la primera tarjeta
            Ext.getCmp('cardHiddenField').setValue(store.data.getAt(0).data.id);
            // Se crean los contenedores con las tarjetas
            for (var i=0;i!=n;i++) {
                var data = store.data.getAt(i).data;
                var html = '<div class="account">'+data.number+'</div>';
                var container = Ext.create('Ext.Container',{
                    html: html,
                    cls: 'accountSelectCarousel'
                });
                Ext.getCmp('cardCarousel').add(container);
            }
        }
    }

});