/*
 * File: app/controller/PayerController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finappsparty.controller.PayerController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#payerCancelAction": {
                tap: 'onPayerCancelActionTap'
            },
            "#payerOkAction": {
                tap: 'onPayerOkActionTap'
            }
        }
    },

    onPayerCancelActionTap: function(button, e, options) {
        this.cancelPayerOperation();
    },

    onPayerOkActionTap: function(button, e, options) {
        this.acceptPayerOperation();
    },

    cancelPayerOperation: function() {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: ' Operación cancelada ',
            indicator: false
        });
        setTimeout(function(){
            Ext.Viewport.setMasked(false);
            Ext.getCmp('payerPanel').hide();
        },1000);
    },

    acceptPayerOperation: function() {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: 'Realizando la<br/>transferencia ...'
        });
        setTimeout(function(){
            Ext.Viewport.setMasked(false);
            Ext.getCmp('payerPanel').hide();
        },1000);
    }

});